# Generated by Django 4.1 on 2022-08-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(default=1)),
                ('stage_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='stage',
            field=models.ForeignKey(db_column='stage_number', default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.stage'),
        ),
    ]
